### PR TITLE
A few implementations

### PR DESCRIPTION
**Pull request by BiatuAutMiahn**
- Checks for /boot/grubfm/menu.cfg
- If user menu exists, adds 'Boot Menu' to hot bar.
- Added glowing hot bar icon for focused section.
- Overlayed a modified `slack/icons/search.png` onto `slack/icons/hdd.png` as osdetect replacement icon.
- Set menu.cfg menu to default on boot if exists.

image

### CODE REVIEW

**Comment by a1ive** [comment]
I think it's too complex.
Maybe we can just modify osdetect.sh to load /boot/grubfm/menu.cfg if it exists.

**Comment by steve6375** [comment]
same as using /boot/grubfm/config ???

**Comment by a1ive** [comment]
Or we can replace [F5] PXE boot menu.It's useless if not booting from network.

**Comment by BiatuAutMiahn** [comment]
If you consider a standard live cd distro's isolinux boot menu, we start at a boot menu, and have various options available via the function keys.

The suggestions in the related issue using `boot/grubfm/config` might cause confusion to those simply trying to add a few boot entries, and less interoperability. (ie; menu.cfg with hotbar footer being run on normal grub2 could cause issues)

**Comment by BiatuAutMiahn** [comment]
Can we merge this? Or are you waiting on me?

**Pull request closed without merging**
